/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import javax.swing.table.DefaultTableModel;
import entity.*;
import javax.swing.JOptionPane;

/**
 *
 * @author jordan
 */
public class BackOfficeForm extends javax.swing.JFrame {
    private final DefaultTableModel model;
    private Bisnis bisnis;
    private int index;
    private int row;
    /**
     * Creates new form BackOffice
     */
    public BackOfficeForm(Bisnis bisnis) {
        initComponents();
        this.bisnis = bisnis;
        this.model = (DefaultTableModel) tbProduk.getModel();
        this.model.setRowCount(0);
        
        populateTable(bisnis);
    }
    
    public void populateTable(Bisnis bisnis) {
        for(int i = 0; i < this.bisnis.getProdukTotal(); i++) {
            this.model.addRow(new Object[]{this.bisnis.getProduk(i).getId(), 
                this.bisnis.getProduk(i).getNama(), 
                this.bisnis.getProduk(i).getHarga(),
                this.bisnis.getProduk(i).getStok(),
        });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbProduk = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfNamaProd = new javax.swing.JTextField();
        btnTambah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnKembali = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        tfStok = new javax.swing.JTextField();
        tfHarga = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 20)); // NOI18N
        jLabel1.setText("KomaPOS Back Office Form");

        tbProduk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nama", "Harga", "Stok"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbProduk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbProdukMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbProduk);

        jLabel2.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 14)); // NOI18N
        jLabel2.setText("Nama Produk");

        jLabel3.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 14)); // NOI18N
        jLabel3.setText("Harga");

        jLabel4.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 14)); // NOI18N
        jLabel4.setText("Stok");

        tfNamaProd.setFont(new java.awt.Font("Plus Jakarta Sans Medium", 0, 14)); // NOI18N
        tfNamaProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNamaProdActionPerformed(evt);
            }
        });

        btnTambah.setFont(new java.awt.Font("Plus Jakarta Sans Medium", 0, 14)); // NOI18N
        btnTambah.setText("Tambah Produk");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnHapus.setFont(new java.awt.Font("Plus Jakarta Sans Medium", 0, 14)); // NOI18N
        btnHapus.setText("Hapus Produk");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnKembali.setFont(new java.awt.Font("Plus Jakarta Sans Medium", 0, 14)); // NOI18N
        btnKembali.setText("Kembali");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });

        btnEdit.setFont(new java.awt.Font("Plus Jakarta Sans Medium", 0, 14)); // NOI18N
        btnEdit.setText("Edit Produk");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        tfStok.setFont(new java.awt.Font("Plus Jakarta Sans Medium", 0, 14)); // NOI18N
        tfStok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfStokActionPerformed(evt);
            }
        });

        tfHarga.setFont(new java.awt.Font("Plus Jakarta Sans Medium", 0, 14)); // NOI18N
        tfHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfHargaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 167, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(btnEdit)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnHapus)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnTambah))
                                    .addComponent(btnKembali, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfStok, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tfNamaProd)
                                    .addComponent(tfHarga, javax.swing.GroupLayout.Alignment.TRAILING)))))
                    .addComponent(jLabel1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tfNamaProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfStok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnTambah)
                            .addComponent(btnHapus)
                            .addComponent(btnEdit))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnKembali)))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // catch values
        String namaProd = tfNamaProd.getText();
        double harga = Double.parseDouble(tfHarga.getText());
        int stok = tfStok.getText() == null ? 0 : Integer.parseInt(tfStok.getText());
        
        // call add method
        boolean tambah = this.bisnis.tambahProduk(namaProd, harga, stok);
        
        // if add returns false, means that produk.size == 9
        if(!tambah) JOptionPane.showMessageDialog(null, "Jumlah produk maksimal");
        else {
            this.index++;
            this.model.addRow(new Object[]{this.bisnis.getProduk(this.index).getId(), 
                this.bisnis.getProduk(this.index).getNama(), 
                this.bisnis.getProduk(this.index).getHarga(),
                this.bisnis.getProduk(this.index).getStok(),
            });
            JOptionPane.showMessageDialog(null, "Berhasil menambah produk");
        }
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        this.index = tbProduk.getSelectedRow();
        
        try{
            this.bisnis.hapusProduk(this.index);
            this.model.removeRow(this.index);
            this.index = -1;
            
            this.tfNamaProd.setText("");
            this.tfHarga.setText("");
            this.tfStok.setText("");
            JOptionPane.showMessageDialog(null, "Berhasil menghapus produk");
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Mohon pilih produk");
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        // TODO add your handling code here:
        new BackOffice(this.bisnis).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        int selectedRow = this.tbProduk.getSelectedRow();
        
        String namaProd = tfNamaProd.getText();
        double harga = Double.parseDouble(tfHarga.getText());
        int stok = tfStok.getText() == null ? 0 : Integer.parseInt(tfStok.getText());
        
        this.bisnis.editProduk(namaProd, (double)harga, (int)stok, this.row);
        this.tbProduk.setValueAt(this.bisnis.getProduk(selectedRow).getId(), selectedRow, 0);
        this.tbProduk.setValueAt(this.bisnis.getProduk(selectedRow).getNama(), selectedRow, 1);
        this.tbProduk.setValueAt(this.bisnis.getProduk(selectedRow).getHarga(), selectedRow, 2);
        this.tbProduk.setValueAt(this.bisnis.getProduk(selectedRow).getStok(), selectedRow, 3);
    }//GEN-LAST:event_btnEditActionPerformed

    private void tbProdukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbProdukMouseClicked
        // TODO add your handling code here:
        this.row = tbProduk.rowAtPoint(evt.getPoint());
        
        if(this.row >= 0) {
            String namaProd = (String) tbProduk.getValueAt(this.row, 1);
            Object harga = tbProduk.getValueAt(this.row, 2);
            Object stok = tbProduk.getValueAt(this.row, 3);
            
            tfNamaProd.setText(namaProd);
            tfHarga.setText(String.valueOf(harga));
            tfStok.setText( String.valueOf(stok));
        }
    }//GEN-LAST:event_tbProdukMouseClicked

    private void tfNamaProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNamaProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNamaProdActionPerformed

    private void tfStokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfStokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfStokActionPerformed

    private void tfHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfHargaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BackOfficeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BackOfficeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BackOfficeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BackOfficeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BackOffice().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnTambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbProduk;
    private javax.swing.JTextField tfHarga;
    private javax.swing.JTextField tfNamaProd;
    private javax.swing.JTextField tfStok;
    // End of variables declaration//GEN-END:variables
}
