/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import javax.swing.table.DefaultTableModel;
import entity.Bisnis;
import javax.swing.JOptionPane;

/**
 *
 * @author jordan
 */
public class BackOffice extends javax.swing.JFrame {
    private final DefaultTableModel model;
    private final DefaultTableModel memberModel;
    private Bisnis bisnis;
    /**
     * Creates new form BackOffice
     */
    public BackOffice() {
        initComponents();
        this.bisnis = new Bisnis();
        this.model = (DefaultTableModel) tbProduk.getModel();
        this.memberModel = (DefaultTableModel) tblMember.getModel();
        this.model.setRowCount(0);
    }
    
    public BackOffice(Bisnis bisnis) {
        initComponents();
        this.model = (DefaultTableModel) tbProduk.getModel();
        this.memberModel = (DefaultTableModel) tblMember.getModel();
        
        this.bisnis = bisnis;
        
        populateTableProduk(bisnis);
        populateTableMember(bisnis);
    }
    
    public void populateTableProduk(Bisnis bisnis) {
        for(int i = 0; i < this.bisnis.getProdukTotal(); i++) {
            this.model.addRow(new Object[]{this.bisnis.getProduk(i).getId(), 
                this.bisnis.getProduk(i).getNama(), 
                this.bisnis.getProduk(i).getHarga(),
                this.bisnis.getProduk(i).getStok(),
        });
        }
    }
    
    public void populateTableMember(Bisnis bisnis) {
        for(int i = 0; i < this.bisnis.getMemberTotal(); i++) {
            this.memberModel.addRow(new Object[]{this.bisnis.getMember(i).getNama(), 
                this.bisnis.getMember(i).getKode(), 
                this.bisnis.getMember(i).getPotongan()
        });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbProduk = new javax.swing.JTable();
        btnTambah = new javax.swing.JButton();
        btnDefault = new javax.swing.JButton();
        btnFO = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblMember = new javax.swing.JTable();
        btnMemberDefault = new javax.swing.JButton();
        btnTambahMember = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 20)); // NOI18N
        jLabel1.setText("KomaPOS Back Office");

        tbProduk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nama", "Harga", "Stok"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbProduk);

        btnTambah.setFont(new java.awt.Font("Plus Jakarta Sans Medium", 0, 14)); // NOI18N
        btnTambah.setText("Manajemen Produk");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnDefault.setFont(new java.awt.Font("Plus Jakarta Sans Medium", 0, 14)); // NOI18N
        btnDefault.setText("Tambah Default");
        btnDefault.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDefaultActionPerformed(evt);
            }
        });

        btnFO.setFont(new java.awt.Font("Plus Jakarta Sans Medium", 0, 14)); // NOI18N
        btnFO.setText("Front Office");
        btnFO.setToolTipText("");
        btnFO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFOActionPerformed(evt);
            }
        });

        tblMember.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama", "Kode", "Potongan"
            }
        ));
        jScrollPane2.setViewportView(tblMember);

        btnMemberDefault.setFont(new java.awt.Font("Plus Jakarta Sans Medium", 0, 14)); // NOI18N
        btnMemberDefault.setText("Tambah Default");
        btnMemberDefault.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMemberDefaultActionPerformed(evt);
            }
        });

        btnTambahMember.setFont(new java.awt.Font("Plus Jakarta Sans Medium", 0, 14)); // NOI18N
        btnTambahMember.setText("Manajemen Member");
        btnTambahMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahMemberActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(btnFO)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDefault)
                        .addGap(18, 18, 18)
                        .addComponent(btnTambah))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 656, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(803, 803, 803)
                        .addComponent(btnMemberDefault)
                        .addGap(18, 18, 18)
                        .addComponent(btnTambahMember)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnTambah)
                    .addComponent(btnDefault)
                    .addComponent(btnFO))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambahMember)
                    .addComponent(btnMemberDefault))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDefaultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDefaultActionPerformed
        // TODO add your handling code here:
        String[] namaProds = {"Produk 1", "Barang 2", "Barang 3", "Barang 4", "Barang 5", "Barang 6", "Barang 7", "Barang 8", "Barang 9"};
        double[] harga = {29000, 28000, 27000, 26000, 25000, 24000, 23000, 22000, 21000};
        int [] stok = {18, 16, 14, 12, 10,  8, 6, 4, 2};
        
        for(int i = 0; i < 9; i++) {
            boolean tambah = this.bisnis.tambahProduk(namaProds[i], harga[i], stok[i]);
            if(!tambah) {
                JOptionPane.showMessageDialog(null, "Gagal menambah produk");
                break;
            }
            this.model.addRow(new Object[]{this.bisnis.getProduk(i).getId(), 
                this.bisnis.getProduk(i).getNama(), 
                this.bisnis.getProduk(i).getHarga(),
                this.bisnis.getProduk(i).getStok(),
            });
        }
    }//GEN-LAST:event_btnDefaultActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        new BackOfficeForm(this.bisnis).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnFOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFOActionPerformed
        // TODO add your handling code here:
        new FrontOffice(this.bisnis).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnFOActionPerformed

    private void btnMemberDefaultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMemberDefaultActionPerformed
        // TODO add your handling code here:
        String[] namaMember = {"Member 1", "Member 2", "Member 3"};
        String[] kodeMember = {"3ms4tu", "3mdu4", "3mt194"};
        double[] potonganMember = {1000, 3000, 9000};
        
        for(int i = 0; i < 3; i++) {
            this.bisnis.tambahMember(namaMember[i], kodeMember[i], potonganMember[i]);
            this.memberModel.addRow(new Object[]{this.bisnis.getMember(i).getNama(),
                this.bisnis.getMember(i).getKode(),
                this.bisnis.getMember(i).getPotongan()
            });
        }
    }//GEN-LAST:event_btnMemberDefaultActionPerformed

    private void btnTambahMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahMemberActionPerformed
        // TODO add your handling code here:
        new MemberForm(this.bisnis).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnTambahMemberActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BackOffice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BackOffice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BackOffice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BackOffice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BackOffice().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDefault;
    private javax.swing.JButton btnFO;
    private javax.swing.JButton btnMemberDefault;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnTambahMember;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbProduk;
    private javax.swing.JTable tblMember;
    // End of variables declaration//GEN-END:variables
}
